
services:
  spc-api:
    container_name: spc-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres-db:5432/ShoppingCart
      USERNAME: postgres
      PASSWORD: 123456
    depends_on:
      - Postgres-DB
    networks:
      - shoppingcart-networks
    restart: unless-stopped

  Postgres-DB:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    networks:
      - shoppingcart-networks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ShoppingCart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - shoppingcart-networks
    depends_on:
      - Postgres-DB
    restart: unless-stopped

networks:
  shoppingcart-networks:
    driver: bridge

volumes:
  postgres_data:
    driver: local
